[tool.poetry]
name = "matsutake"
version = "0.1.0"
description = ""
authors = ["あああ <lanur622@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
